"""Synthetic SLAM sequence generator (fixed design).

This is the generator used by the corrected feasibility study. It models the
runtime setting of the thesis:

* a hidden SLAM pose-error process (AR(1) in signed 6-DoF components) whose
  innovation scale grows with camera motion (and, in the legacy ``coupled``
  error model, with near scene depth);
* corrupted *estimated* depth maps (the GIGO effect: when the error is high,
  the geometry the SLAM system believes in degrades);
* a runtime reliability signal that is a *noisy* observation of the hidden
  error state (in a real system this plays the role of reprojection residuals,
  covariances, or tracking quality) -- deliberately not a deterministic
  function of the true error;
* the IOF target computed offline from the TRUE error and TRUE depth.

Review-driven realism (round 2):

* **Estimated motion by default** (``motion_source="estimated"``): the model
  no longer receives true camera motion. The generator composes an accumulated
  estimated trajectory ``T_hat = T_gt (x) T_err`` (error in the local frame)
  and derives the estimated relative motion from ``inv(T_hat[t-1]) @ T_hat[t]``,
  exactly the quantity a running SLAM exposes. ``motion_source="true"`` keeps
  the pre-review behavior for comparison.
* **Degraded reliability variants** (``reliability_mode``): clean / noisy /
  delayed / miscalibrated / masked / intermittent -- the review's concern that
  ``conf = exp(-5*err)`` is unrealistically informative. The stress matrix
  (``scripts/run_feasibility.py --stress``) re-runs the gates under each.
* **Abrupt jump failures** (``jump_prob``, ``jump_scale``): real SLAM fails
  abruptly (motion blur, textureless walls, relocalization jumps), not only by
  smooth AR(1) drift; jumps are essential for warning-lead-time evaluation.
* **Realistic depth corruption** (``depth_corruption="realistic"``): holes
  (far-plane defaults), flying pixels and specular near-spikes on top of the
  Gaussian noise.

Design notes vs. the original scene-scale.ipynb:
  - motion is informative (smoothly varying forward speed + rotation bursts),
    not an almost-constant scalar;
  - the reliability signal is part of the model input;
  - the error model is **depth-decoupled by default** (``error_model="decoupled"``):
    the pose-error scale depends on motion only, and scene depth enters ONLY
    through the IOF target (the geometric 1/Z projection denominator). This is
    the physically correct setting for the thesis hypothesis -- SLAM error is
    generated by the motion/visual pipeline; depth then determines how that
    error manifests in the image plane. It removes the G3 confound of the
    legacy ``error_model="coupled"`` variant, where error scale grew with
    ``motion / depth`` and entangled the two inputs, so the depth channel's
    value could not be isolated (see reports/feasibility.md, G3).

    Note: the archived pre-fix run (reports/feasibility_results_coupled.json)
    used the original generator constants (DEPTH_CHOICES 1.5--25 m, rotation
    weight 0.5); the current DEPTH_CHOICES / ROT_INNOV_WEIGHT are the fixed
    (scene-scale-faithful) ones used by the default decoupled experiment.
"""

from __future__ import annotations

import numpy as np

from .iof import compute_iof, log_so3, se3_to_T

# Scene-scale choices span near object-scanning to far outdoor, mirroring
# Princeton365's mix (285/365 object-scanning sequences at sub-meter scale).
DEPTH_CHOICES = (0.5, 0.8, 1.2, 2.0, 4.0, 8.0, 15.0, 30.0)
DEPTH_CORR = 0.95      # scene-depth temporal correlation
POSE_CORR = 0.90       # AR(1) coefficient of the hidden error process
CONFIDENCE_NOISE = 0.15  # relative observation noise of the reliability signal
ROT_INNOV_WEIGHT = 0.3   # rotation-innovation scale relative to translation
RELIABILITY_MODES = ("clean", "noisy", "delayed", "miscalibrated", "masked",
                     "intermittent")


def _apply_reliability_mode(conf: np.ndarray, mode: str, rng: np.random.RandomState,
                            delay: int = 3, every: int = 5, noise: float = 0.6) -> np.ndarray:
    """Post-process the clean reliability signal into a degraded variant.

    * clean        -- as generated (noisy observation of the error state)
    * noisy        -- much larger observation noise (signal still biased)
    * delayed      -- lagged by ``delay`` frames (stale observation)
    * miscalibrated-- inverted: confidence reads HIGH when the error is high
                      (a wrongly-calibrated sensor; a robust model must
                      re-learn the mapping)
    * masked       -- constant 0.5: no error-state information at all
    * intermittent -- available only every ``every``-th frame
    """
    conf = np.asarray(conf, dtype=np.float64)
    if mode == "clean":
        return conf
    if mode == "noisy":
        return np.clip(conf * (1.0 + noise * rng.randn(len(conf))), 0.0, 1.0)
    if mode == "delayed":
        out = np.full_like(conf, 0.5)
        out[delay:] = conf[:-delay]
        return out
    if mode == "miscalibrated":
        return np.clip(1.0 - conf, 0.0, 1.0)
    if mode == "masked":
        return np.full_like(conf, 0.5)
    if mode == "intermittent":
        out = np.full_like(conf, 0.5)
        out[::every] = conf[::every]
        return out
    raise ValueError(f"unknown reliability_mode {mode!r} (choices: {RELIABILITY_MODES})")


def generate_sequence(
    seq_len: int = 80,
    base_depth: float | None = None,
    seed: int = 0,
    error_model: str = "decoupled",
    motion_source: str = "estimated",
    reliability_mode: str = "clean",
    jump_prob: float = 0.0,
    jump_scale: float = 3.0,
    depth_corruption: str = "gaussian",
    num_samples: int = 200,
) -> dict:
    """Generate one synthetic sequence with runtime features and IOF targets.

    Args:
        seq_len: number of frames.
        base_depth: scene depth (m); randomly drawn from DEPTH_CHOICES if None.
        seed: RNG seed.
        error_model: "decoupled" (default; error scale depends on motion only,
            depth enters solely through the IOF 1/Z target -- the G3 fix) or
            "coupled" (legacy; error scale also grows with 1/depth, entangling
            motion and depth -- kept for comparison; the archived pre-fix run
            used the original generator constants).
        motion_source: "estimated" (default; relative motion derived from an
            accumulated estimated trajectory whose pose error corrupts it --
            the faithful runtime setting) or "true" (pre-review behavior,
            clean true motion, kept for comparison).
        reliability_mode: one of RELIABILITY_MODES (see
            ``_apply_reliability_mode``). Default "clean".
        jump_prob: per-frame probability of an abrupt error jump (0 = no
            jumps, the smooth AR(1) process only).
        jump_scale: jump magnitude relative to the per-frame innovation scale.
        depth_corruption: "gaussian" (default) or "realistic" (adds holes,
            flying pixels and specular near-spikes to the estimated depth).
        num_samples: per-frame IOF pixel samples (the FlowAUC target and the
            label-noise sensitivity sweep, round-3 review fix M8).

    Returns a dict with arrays of shape (T, ...):
        motion       (T, 6)  |translation|, |rotation| of the ESTIMATED
                             relative motion per frame (runtime input)
        depth_stats  (T, 4)  median, q25, q75, std of the *estimated* depth
        confidence   (T, 1)  (possibly degraded) reliability signal (runtime)
        iof          (T,)    true induced optical flow (offline target)
        flow_samples (T, S)  per-pixel induced-flow magnitudes at each frame
                             (NaN for invalid samples) -- the FlowAUC target
        depth_samples (T, Sd) true scene-depth samples per frame -- the input
                             to the official metric's depth-distribution fit
        T_gt, T_hat  (T, 4, 4) accumulated GT and estimated world-to-camera
                             poses (the official-protocol alignment input)
        trans_err_mag (T,)   true translation-error magnitude (train-time only)
        rot_err_mag   (T,)   true rotation-error magnitude (train-time only)
        median       (T,)    true median depth (train-time only)
    """
    if error_model not in ("coupled", "decoupled"):
        raise ValueError(f"error_model must be 'coupled' or 'decoupled', got {error_model!r}")
    if motion_source not in ("true", "estimated"):
        raise ValueError(f"motion_source must be 'true' or 'estimated', got {motion_source!r}")
    if reliability_mode not in RELIABILITY_MODES:
        raise ValueError(f"reliability_mode must be one of {RELIABILITY_MODES}, "
                         f"got {reliability_mode!r}")
    if depth_corruption not in ("gaussian", "realistic"):
        raise ValueError(f"depth_corruption must be 'gaussian' or 'realistic', "
                         f"got {depth_corruption!r}")
    rng = np.random.RandomState(seed)
    if base_depth is None:
        base_depth = float(rng.choice(DEPTH_CHOICES))
    trans_err = np.zeros(3, dtype=np.float64)
    rot_err = np.zeros(3, dtype=np.float64)
    depth_base = base_depth
    speed = 0.05
    # accumulated trajectories for the estimated-motion model:
    #   T_gt_cum[t] = T_gt_cum[t-1] (x) T_rel_true[t]
    #   T_hat_cum[t] = T_gt_cum[t] (x) T_err[t]   (error in the local frame)
    T_gt_cum = np.eye(4, dtype=np.float64)
    T_hat_prev = np.eye(4, dtype=np.float64)

    xs = np.linspace(-1, 1, 256)
    ys = np.linspace(-1, 1, 256)
    Xg, Yg = np.meshgrid(xs, ys)

    rec = {
        "motion": [],
        "depth_stats": [],
        "confidence": [],
        "iof": [],
        "flow_samples": [],
        "depth_samples": [],
        "T_gt": [],
        "T_hat": [],
        "trans_err_mag": [],
        "rot_err_mag": [],
        "median": [],
    }
    conf_clean = []

    for t in range(seq_len):
        # --- ground-truth scene depth (slowly drifting, spatially structured) ---
        depth_base = DEPTH_CORR * depth_base + (1 - DEPTH_CORR) * base_depth + 0.05 * rng.randn()
        depth_base = max(depth_base, 0.5)
        D = depth_base * (
            1.0
            + 0.15 * np.sin(3.0 * Xg + 0.2 * t)
            + 0.10 * np.cos(2.0 * Yg - 0.3 * t)
        )
        D = np.maximum(D + 0.02 * depth_base * rng.randn(256, 256), 0.5).astype(np.float64)

        # --- informative camera motion (what SLAM estimates) ---
        speed = 0.90 * speed + 0.10 * (0.03 + 0.05 * rng.rand())
        trans_true = np.array([speed, 0.0, 0.0]) + 0.02 * rng.randn(3)
        if rng.rand() < 0.06:  # occasional rotation burst
            rot_true = rng.uniform(-0.12, 0.12, 3)
        else:
            rot_true = 0.01 * rng.randn(3)
        motion_mag = np.linalg.norm(trans_true) + 0.3 * np.linalg.norm(rot_true)

        # --- hidden SLAM error: AR(1), scale grows with motion; depth enters
        #     ONLY the target (1/Z IOF denominator) in the decoupled model.
        if error_model == "decoupled":
            error_scale = 0.005 + 0.05 * motion_mag
        else:  # legacy "coupled": error scale also grows with near depth
            depth_factor = 1.0 / (np.median(D) + 1e-3)
            error_scale = 0.005 + 0.05 * motion_mag * depth_factor
        trans_err = POSE_CORR * trans_err + error_scale * rng.randn(3)
        rot_err = POSE_CORR * rot_err + (error_scale * ROT_INNOV_WEIGHT) * rng.randn(3)

        # --- abrupt jump failures (motion blur, relocalization events) ---
        if jump_prob > 0.0 and rng.rand() < jump_prob:
            trans_err = trans_err + jump_scale * error_scale * rng.randn(3)
            rot_err = rot_err + jump_scale * error_scale * ROT_INNOV_WEIGHT * rng.randn(3)
        err_mag = np.linalg.norm(trans_err)

        # --- corrupted estimated depth (GIGO): input side degrades with error ---
        corruption = rng.randn(256, 256) * (err_mag * 5.0)
        D_est = np.maximum(D + corruption, 0.5)
        if depth_corruption == "realistic":
            holes = rng.rand(256, 256) < 0.05          # far-plane defaults
            D_est[holes] = 50.0
            flying = rng.rand(256, 256) < 0.02         # flying pixels (spikes)
            D_est[flying] += depth_base * 5.0 * np.abs(rng.randn())
            spec = rng.rand(256, 256) < 0.01           # specular near-spikes
            D_est[spec] = 0.3
        D_est = np.maximum(D_est, 0.5)

        # --- target: IOF from TRUE error + TRUE depth (offline GT); the
        #     per-pixel flow samples are the FlowAUC target (round-3 M5) ---
        iof, flows = compute_iof(
            se3_to_T(trans_err, rot_err), D,
            num_samples=num_samples, seed=12345 + t, return_flows=True,
        )
        # true scene-depth subsample for the official metric's depth-
        # distribution fit (round-3 C1 machinery)
        depth_samp = D.ravel()[rng.choice(D.size, 512, replace=False)]

        # --- runtime reliability signal: noisy observation of the error state ---
        noisy_err = err_mag * (1.0 + CONFIDENCE_NOISE * rng.randn())
        conf_clean.append(float(np.exp(-5.0 * max(noisy_err, 0.0))))

        # --- runtime motion feature: true relative motion, or the ESTIMATED
        #     relative motion derived from the accumulated estimated trajectory
        #     M_hat = inv(T_hat[t-1]) @ T_hat[t]  (corrupted by the pose error) ---
        T_rel_true = se3_to_T(trans_true, rot_true)
        T_gt_cum = T_gt_cum @ T_rel_true
        T_hat_cum = T_gt_cum @ se3_to_T(trans_err, rot_err)
        if motion_source == "estimated":
            M_hat = np.linalg.inv(T_hat_prev) @ T_hat_cum
            m_trans = np.abs(M_hat[:3, 3])
            m_rot = np.abs(log_so3(M_hat[:3, :3]))
        else:  # "true": pre-review behavior, clean true motion
            m_trans = np.abs(trans_true)
            m_rot = np.abs(rot_true)
        T_hat_prev = T_hat_cum

        d = D_est.ravel()
        rec["motion"].append(np.concatenate([m_trans, m_rot]))
        rec["depth_stats"].append(
            [float(np.median(d)), float(np.percentile(d, 25)),
             float(np.percentile(d, 75)), float(np.std(d))]
        )
        rec["iof"].append(iof)
        rec["flow_samples"].append(flows)
        rec["depth_samples"].append(depth_samp)
        # poses stored as WORLD-TO-CAMERA (the proposal's explicit convention,
        # matching iof.camera_centers / relative_error_pose): the accumulated
        # chains above are camera-to-world, so invert per frame.
        rec["T_gt"].append(np.linalg.inv(T_gt_cum))
        rec["T_hat"].append(np.linalg.inv(T_hat_cum))
        rec["trans_err_mag"].append(float(np.linalg.norm(trans_err)))
        rec["rot_err_mag"].append(float(np.linalg.norm(rot_err)))
        rec["median"].append(float(np.median(D)))

    rec["confidence"] = _apply_reliability_mode(np.array(conf_clean), reliability_mode, rng)
    return {k: np.array(v, dtype=np.float64) for k, v in rec.items()}
