"""Synthetic SLAM sequence generator (fixed design).

This is the generator used by the corrected feasibility study. It models the
runtime setting of the thesis:

* a hidden SLAM pose-error process (AR(1) in signed 6-DoF components) whose
  innovation scale grows with camera motion (and, in the legacy ``coupled``
  error model, with near scene depth);
* corrupted *estimated* depth maps (the GIGO effect: when the error is high,
  the geometry the SLAM system believes in degrades);
* a runtime reliability signal that is a *noisy* observation of the hidden
  error state (in a real system this plays the role of reprojection residuals,
  covariances, or tracking quality) -- deliberately not a deterministic
  function of the true error;
* the IOF target computed offline from the TRUE error and TRUE depth.

Design notes vs. the original scene-scale.ipynb:
  - motion is informative (smoothly varying forward speed + rotation bursts),
    not an almost-constant scalar;
  - the reliability signal is part of the model input;
  - the error model is **depth-decoupled by default** (``error_model="decoupled"``):
    the pose-error scale depends on motion only, and scene depth enters ONLY
    through the IOF target (the geometric 1/Z projection denominator). This is
    the physically correct setting for the thesis hypothesis -- SLAM error is
    generated by the motion/visual pipeline; depth then determines how that
    error manifests in the image plane. It removes the G3 confound of the
    legacy ``error_model="coupled"`` variant, where error scale grew with
    ``motion / depth`` and entangled the two inputs, so the depth channel's
    value could not be isolated (see reports/feasibility.md, G3).

    Note: the archived pre-fix run (reports/feasibility_results_coupled.json)
    used the original generator constants (DEPTH_CHOICES 1.5--25 m, rotation
    weight 0.5); the current DEPTH_CHOICES / ROT_INNOV_WEIGHT are the fixed
    (scene-scale-faithful) ones used by the default decoupled experiment.
"""

from __future__ import annotations

import numpy as np

from .iof import compute_iof

# Scene-scale choices span near object-scanning to far outdoor, mirroring
# Princeton365's mix (285/365 object-scanning sequences at sub-meter scale).
DEPTH_CHOICES = (0.5, 0.8, 1.2, 2.0, 4.0, 8.0, 15.0, 30.0)
DEPTH_CORR = 0.95      # scene-depth temporal correlation
POSE_CORR = 0.90       # AR(1) coefficient of the hidden error process
CONFIDENCE_NOISE = 0.15  # relative observation noise of the reliability signal
ROT_INNOV_WEIGHT = 0.3   # rotation-innovation scale relative to translation


def generate_sequence(
    seq_len: int = 80,
    base_depth: float | None = None,
    seed: int = 0,
    error_model: str = "decoupled",
) -> dict:
    """Generate one synthetic sequence with runtime features and IOF targets.

    Args:
        seq_len: number of frames.
        base_depth: scene depth (m); randomly drawn from DEPTH_CHOICES if None.
        seed: RNG seed.
        error_model: "decoupled" (default; error scale depends on motion only,
            depth enters solely through the IOF 1/Z target -- the G3 fix) or
            "coupled" (legacy; error scale also grows with 1/depth, entangling
            motion and depth -- kept for comparison; the archived pre-fix run
            used the original generator constants).

    Returns a dict with arrays of shape (T, ...):
        motion       (T, 6)  |translation|, |rotation| per frame (runtime input)
        depth_stats  (T, 4)  median, q25, q75, std of the *estimated* depth
        confidence   (T, 1)  noisy reliability signal (runtime input)
        iof          (T,)    true induced optical flow (offline target)
        trans_err_mag (T,)   true translation-error magnitude (train-time only)
        rot_err_mag   (T,)   true rotation-error magnitude (train-time only)
        median       (T,)    true median depth (train-time only)
    """
    if error_model not in ("coupled", "decoupled"):
        raise ValueError(f"error_model must be 'coupled' or 'decoupled', got {error_model!r}")
    rng = np.random.RandomState(seed)
    if base_depth is None:
        base_depth = float(rng.choice(DEPTH_CHOICES))
    trans_err = np.zeros(3, dtype=np.float64)
    rot_err = np.zeros(3, dtype=np.float64)
    depth_base = base_depth
    speed = 0.05

    xs = np.linspace(-1, 1, 256)
    ys = np.linspace(-1, 1, 256)
    Xg, Yg = np.meshgrid(xs, ys)

    rec = {
        "motion": [],
        "depth_stats": [],
        "confidence": [],
        "iof": [],
        "trans_err_mag": [],
        "rot_err_mag": [],
        "median": [],
    }

    for t in range(seq_len):
        # --- ground-truth scene depth (slowly drifting, spatially structured) ---
        depth_base = DEPTH_CORR * depth_base + (1 - DEPTH_CORR) * base_depth + 0.05 * rng.randn()
        depth_base = max(depth_base, 0.5)
        D = depth_base * (
            1.0
            + 0.15 * np.sin(3.0 * Xg + 0.2 * t)
            + 0.10 * np.cos(2.0 * Yg - 0.3 * t)
        )
        D = np.maximum(D + 0.02 * depth_base * rng.randn(256, 256), 0.5).astype(np.float64)

        # --- informative camera motion (what SLAM estimates) ---
        speed = 0.90 * speed + 0.10 * (0.03 + 0.05 * rng.rand())
        trans_true = np.array([speed, 0.0, 0.0]) + 0.02 * rng.randn(3)
        if rng.rand() < 0.06:  # occasional rotation burst
            rot_true = rng.uniform(-0.12, 0.12, 3)
        else:
            rot_true = 0.01 * rng.randn(3)
        motion_mag = np.linalg.norm(trans_true) + 0.3 * np.linalg.norm(rot_true)

        # --- hidden SLAM error: AR(1), scale grows with motion; depth enters
        #     ONLY the target (1/Z IOF denominator) in the decoupled model.
        if error_model == "decoupled":
            error_scale = 0.005 + 0.05 * motion_mag
        else:  # legacy "coupled": error scale also grows with near depth
            depth_factor = 1.0 / (np.median(D) + 1e-3)
            error_scale = 0.005 + 0.05 * motion_mag * depth_factor
        trans_err = POSE_CORR * trans_err + error_scale * rng.randn(3)
        rot_err = POSE_CORR * rot_err + (error_scale * ROT_INNOV_WEIGHT) * rng.randn(3)
        err_mag = np.linalg.norm(trans_err)

        # --- corrupted estimated depth (GIGO): input side degrades with error ---
        corruption = rng.randn(256, 256) * (err_mag * 5.0)
        D_est = np.maximum(D + corruption, 0.5)

        # --- target: IOF from TRUE error + TRUE depth (offline GT) ---
        from .iof import se3_to_T

        iof = compute_iof(se3_to_T(trans_err, rot_err), D, num_samples=200, seed=12345 + t)

        # --- runtime reliability signal: noisy observation of the error state ---
        noisy_err = err_mag * (1.0 + CONFIDENCE_NOISE * rng.randn())
        confidence = float(np.exp(-5.0 * max(noisy_err, 0.0)))

        d = D_est.ravel()
        rec["motion"].append(np.concatenate([np.abs(trans_true), np.abs(rot_true)]))
        rec["depth_stats"].append(
            [float(np.median(d)), float(np.percentile(d, 25)),
             float(np.percentile(d, 75)), float(np.std(d))]
        )
        rec["confidence"].append(confidence)
        rec["iof"].append(iof)
        rec["trans_err_mag"].append(float(np.linalg.norm(trans_err)))
        rec["rot_err_mag"].append(float(np.linalg.norm(rot_err)))
        rec["median"].append(float(np.median(D)))

    return {k: np.array(v, dtype=np.float64) for k, v in rec.items()}
